# Generated by Django 5.1.3 on 2024-12-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_migrate_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
